name       : adwaita-icon-theme
version    : 3.24.0
release    : 10
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/adwaita-icon-theme/3.24/adwaita-icon-theme-3.24.0.tar.xz : ccf79ff3bd340254737ce4d28b87f0ccee4b3358cd3cd5cd11dc7b42f41b272a
license    :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary    : Adwaita Icon Theme
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
