name        : adwaita-icon-theme
version     : 3.18.0
release     : 6
source     :
    - http://ftp.gnome.org/pub/gnome/sources/adwaita-icon-theme/3.18/adwaita-icon-theme-3.18.0.tar.xz : 5e9ce726001fdd8ee93c394fdc3cdb9e1603bbed5b7c62df453ccf521ec50e58
license     :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary     : Adwaita Icon Theme
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
description : |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
