name       : adwaita-icon-theme
version    : 3.22.0
release    : 9
source     :
    - http://ftp.gnome.org/pub/gnome/sources/adwaita-icon-theme/3.22/adwaita-icon-theme-3.22.0.tar.xz : c18bf6e26087d9819a962c77288b291efab25d0419b73d909dd771716a45dcb7
license    :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary    : Adwaita Icon Theme
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
