name       : adwaita-icon-theme
version    : 3.32.0
release    : 15
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/3.32/adwaita-icon-theme-3.32.0.tar.xz : 698db6e407bb987baec736c6a30216dfc0317e3ca2403c7adf3a5aa46c193286
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icon-naming-utils)
    - pkgconfig(librsvg-2.0)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
