name       : adwaita-icon-theme
version    : 3.36.0
release    : 17
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/3.36/adwaita-icon-theme-3.36.0.tar.xz : 1a172112b6da482d3be3de6a0c1c1762886e61e12b4315ae1aae9b69da1ed518
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icon-naming-utils)
    - pkgconfig(librsvg-2.0)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
