name       : adwaita-icon-theme
version    : '41.0'
release    : 22
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/41/adwaita-icon-theme-41.0.tar.xz : ef5339d8c35fcad5d10481b70480803f0fa20b3d3cbc339238fcaceeaee01eba
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
