name       : adwaita-icon-theme
version    : 3.26.1
release    : 12
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/3.26/adwaita-icon-theme-3.26.1.tar.xz : 28ba7392c7761996efd780779167ea6c940eedfb1bf37cfe9bccb7021f54d79d
license    :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary    : Adwaita Icon Theme
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
