name       : adwaita-icon-theme
version    : '40.0'
release    : 20
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/40/adwaita-icon-theme-40.rc.tar.xz : d794a492e8e7db33bdc19898effabc1f1205302e166da522c5351a8eba9da404
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
