name       : adwaita-icon-theme
version    : '3.20'
release    : 7
source     :
    - http://ftp.gnome.org/pub/gnome/sources/adwaita-icon-theme/3.20/adwaita-icon-theme-3.20.tar.xz : 7a0a887349f340dd644032f89d81264b694c4b006bd51af1c2c368d431e7ae35
license    :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary    : Adwaita Icon Theme
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
patterns   :
    - devel: /usr/share/pkgconfig
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
