name       : adwaita-icon-theme
version    : 40.1.1
release    : 21
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/40/adwaita-icon-theme-40.1.1.tar.xz : 0b6c436ed6ad9887a88ada1f72a0197b1eb73b020d8d344abab4c7fa7250f8f6
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(librsvg-2.0)
    - inkscape
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
