name       : adwaita-icon-theme
version    : 3.26.0
release    : 11
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/3.26/adwaita-icon-theme-3.26.0.tar.xz : 9cad85de19313f5885497aceab0acbb3f08c60fcd5fa5610aeafff37a1d12212
license    :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary    : Adwaita Icon Theme
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
