name        : adwaita-icon-theme
version     : 3.16.2
release     : 3
source      :
    - http://ftp.gnome.org/pub/gnome/sources/adwaita-icon-theme/3.16/adwaita-icon-theme-3.16.2.tar.xz : 9c6662ad739cdb32d0ffe638f54e5033c5ea6f53e7f8c2b412ec64b8e7e1b4c2
license     :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary     : Adwaita Icon Theme
builddeps   :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
description : |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
