name       : adwaita-icon-theme
version    : 3.34.0
release    : 16
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/3.34/adwaita-icon-theme-3.34.0.tar.xz : 40b7e91f8263552b64d0f9beff33150291b086618ce498c71bf10035e48c7c7f
license    :
    - CC-BY-SA-3.0
    - LGPL-3.0-or-later
summary    : The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(icon-naming-utils)
    - pkgconfig(librsvg-2.0)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
