name       : adwaita-icon-theme
version    : 3.28.0
release    : 13
source     :
    - https://download.gnome.org/sources/adwaita-icon-theme/3.28/adwaita-icon-theme-3.28.0.tar.xz : 7aae8c1dffd6772fd1a21a3d365a0ea28b7c3988bdbbeafbf8742cda68242150
license    :
    - LGPL-3.0
    - CC-BY-SA-3.0
summary    : Adwaita Icon Theme
description: |
    The Adwaita Icon Theme package contains an assortment of non-scalable icons of different sizes and themes.
component  : desktop.gnome.core
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(icon-naming-utils)
rundeps    :
    - hicolor-icon-theme
patterns   :
    - devel : /usr/share/pkgconfig
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
